# From GAIA L1

task_description: One of the sons of Hreidmar, who guarded his house, had a journal named after him. In 2014 this journal published and article by Emily Midkiff, in which a word quoted from two authors expressed distaste for how dragons were depicted. What was that word?

expected_answer: fluffy
