# From GAIA L1

task_description: Ali Khan's 2015+ TV show featured a budget restaurant where he had New Mexican food, and two winners of the James Beard award recommended the same restaurant in a book. Find that book's complete title, converting any numbers to plain text.

expected_answer: Five Hundred Things To Eat Before It's Too Late and the Very Best Places to Eat Them
