
PageLogger:
  level: DEBUG  # DEBUG, INFO, WARNING, ERROR, CRITICAL, or NONE.
  path: ./pagelogs/retrieval_2

client:
  model: gpt-4o-2024-08-06
  provider: trapi  # openai, azure_openai, or trapi
  # api_key: sk-  # only for openai
  temperature: 0.8
  max_completion_tokens: 4096
  presence_penalty: 0.0
  frequency_penalty: 0.0
  top_p: 1.0
  max_retries: 65535
  ChatCompletionClientRecorder:  # Provides record & replay functionality
    enabled: 0  # Only works for AssistantAgent currently
    mode: replay  # record, replay, or pass to use the client without ChatCompletionClientRecorder
    session_name: ./sessions/retrieval_2/session.json

MemoryController:
  generalize_task: 1
  revise_generalized_task: 1
  generate_topics: 1
  validate_memos: 1
  max_memos_to_retrieve: 1
  MemoryBank:
    path: ./memory_bank/retrieval_2
    relevance_conversion_threshold: 1.7
    n_results: 25
    distance_threshold: 100

evaluations:
  - eval_function:
      function_name: eval_retrieval_2
      module_path: ./eval_functions/eval_retrieval_2.py
    runs:
      - partition_index_filename: ./index.txt
        partitions_filename: ./partitions.txt
        task_pairs:
          - [./data_files/tasks/gaia_0r.yaml, ./data_files/tasks/gaia_0.yaml]
          - [./data_files/tasks/gaia_1r.yaml, ./data_files/tasks/gaia_1.yaml]
          - [./data_files/tasks/gaia_2r.yaml, ./data_files/tasks/gaia_2.yaml]
          - [./data_files/tasks/gaia_3r.yaml, ./data_files/tasks/gaia_3.yaml]
          - [./data_files/tasks/gaia_4r.yaml, ./data_files/tasks/gaia_4.yaml]
          - [./data_files/tasks/gaia_5r.yaml, ./data_files/tasks/gaia_5.yaml]
          - [./data_files/tasks/gaia_6r.yaml, ./data_files/tasks/gaia_6.yaml]
          - [./data_files/tasks/gaia_7r.yaml, ./data_files/tasks/gaia_7.yaml]
          - [./data_files/tasks/gaia_8r.yaml, ./data_files/tasks/gaia_8.yaml]
          - [./data_files/tasks/gaia_9r.yaml, ./data_files/tasks/gaia_9.yaml]
#        tasks:
#          - data_files/tasks/10_liars.yaml
#          - data_files/tasks/100_vampires.yaml
#          - data_files/tasks/autogen_package.yaml
#          - data_files/tasks/cell_towers_1.yaml
#          - data_files/tasks/cell_towers_2.yaml
#        insights:
#          - data_files/insights/add_topic.yaml
#          - data_files/insights/cell_towers_2_demo.yaml
#          - data_files/insights/liar_advice.yaml
#        task_insight_relevance:  # Rows and columns represent (respectively) the tasks and insights listed above.
#          - [0, 0, 2]  # 2 denotes a mutually relevant task-insight pair, stored in memory.
#          - [0, 0, 1]  # 1 denotes a mutually relevant task-insight pair, not stored in memory.
#          - [2, 0, 0]  # 0 denotes a mutually irrelevant task-insight pair.
#          - [0, 1, 0]
#          - [0, 2, 0]
